In [428]:
# Import library
import numpy as np

from numpy import pi

In [429]:
#!pip install numpy

1. Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)

In [430]:
#a =np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype=float, delimiter=',', usecols=(0,1,2,3))
#a =np.genfromtxt('iris.data', dtype=float, delimiter=',', usecols=(0,1,2,3))
def remove_by_target_index(d, i):
    return d[:,:i]

d =np.genfromtxt('iris.data', dtype=float, delimiter=',')

d2d = remove_by_target_index(d, 4)

print(d2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

2. Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)

In [431]:
print('Shape', d2d.shape)
print('Num Dimensions: ', d2d.ndim)

Shape (150, 4)
Num Dimensions:  2


3. Порахувати mean, median, standard deviation для 1-ї колонки

In [432]:
first_col = d2d[:, 0]

print("Mean: ", np.mean(first_col))
print("Median: ", np.median(first_col))
print("Standard deviation: ", np.std(first_col))

Mean:  5.843333333333334
Median:  5.8
Standard deviation:  0.8253012917851409


4. Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)

In [433]:
random_indexes = np.random.choice(d2d.size, 20, replace=False)
np.put(d2d, random_indexes, np.nan)
print(d2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 nan]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 nan]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 nan 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 nan 0.2]
 [5.1 nan 1.7 0.5]
 [4.8 nan 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 nan]
 [4.8 3.  nan 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 nan]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

5. Знайти позиції вставлених значень np.nan в 1-й колонці

In [434]:
nan_pos_first_col = np.where(np.isnan(first_col))
print(nan_pos_first_col)

(array([ 87, 103, 109, 122]),)


6. Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)

In [435]:
filtered_data = d2d[(d2d[:, 2] > 1.5) & (d2d[:, 0] < 5.0)]
print(filtered_data)

[[4.8 3.4 1.6 0.2]
 [4.8 nan 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


7. Замінити всі значення np.nan на 0

In [436]:
d2d = np.nan_to_num(d2d, nan=0.0)
print(d2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0. ]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0. ]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 0.  1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 0.  0.2]
 [5.1 0.  1.7 0.5]
 [4.8 0.  1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0. ]
 [4.8 3.  0.  0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0. ]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

8. Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю

In [437]:
uni = np.unique(d2d, return_counts=True)
print("Unique values = ", uni[0])
print("Count unique values = ", uni[1])

Unique values =  [0.  0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.
 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6
 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4
 7.6 7.7 7.9]
Count unique values =  [20  5 26  7  6  1  1  7  4  6 18 19 26 11  6 12  7  6  5  6 12  6 11  4
  9 14 10 27 12 13  7 11  8  4  4  6  5  6  4  5  3  8  9  7  6  9 11 14
 17  6  3  8 10 12 11 10  5  8  9  4  8  8  5  3 10  3  5  1  1  2  1  1
  1  3  1]


9. Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)

In [438]:
top, bottom  = np.split(d2d, 2, axis = 0)

print("Shape top part = ", top.shape)
print("Shape bottom part = ", bottom.shape)
print("Top part = ", top)
print("Bottom part =", bottom)

Shape top part =  (75, 4)
Shape bottom part =  (75, 4)
Top part =  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0. ]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0. ]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 0.  1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 0.  0.2]
 [5.1 0.  1.7 0.5]
 [4.8 0.  1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0. ]
 [4.8 3.  0.  0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0. ]
 [

10. Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням

In [439]:
top = top[np.argsort(top[:, 0])]
bottom = bottom[np.argsort(bottom[:, 0])[::-1]]
print("Sorted top: ", top)
print("Sorted bottom", bottom)

Sorted top:  [[4.3 3.  1.1 0. ]
 [4.4 2.9 1.4 0. ]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.6 0.  0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.  0.  0.3]
 [4.8 0.  1.9 0.2]
 [4.8 3.1 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [5.  3.5 1.6 0.6]
 [5.  3.3 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.  3.4 1.5 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.  2.  3.5 1. ]
 [5.  3.6 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.1 3.8 1.9 0. ]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.3]
 [5.1 0.  1.5 0.3]
 [5.1 3.7 1.5 0.4]
 [5.1 0.  1.7 0.5]
 [5.2 2.7 3.9 1.4]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [5.3 3.7 1.5 0. ]
 [5.4 3.9 1.3 0.4]
 [5.4 3.9 1.7 0.4]
 [5.4 3.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.7 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [5.5 2.3 4.  1.3]
 [5.5 4.2 1.4 0.2]
 [5.6 2.9 3.6 1.3]

11. Зібрати обидва массиви в одне ціле

In [440]:
combine = np.vstack((top, bottom))
print(combine)

[[4.3 3.  1.1 0. ]
 [4.4 2.9 1.4 0. ]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.6 0.  0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.  0.  0.3]
 [4.8 0.  1.9 0.2]
 [4.8 3.1 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [5.  3.5 1.6 0.6]
 [5.  3.3 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.  3.4 1.5 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.  2.  3.5 1. ]
 [5.  3.6 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.1 3.8 1.9 0. ]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.3]
 [5.1 0.  1.5 0.3]
 [5.1 3.7 1.5 0.4]
 [5.1 0.  1.7 0.5]
 [5.2 2.7 3.9 1.4]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [5.3 3.7 1.5 0. ]
 [5.4 3.9 1.3 0.4]
 [5.4 3.9 1.7 0.4]
 [5.4 3.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.7 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [5.5 2.3 4.  1.3]
 [5.5 4.2 1.4 0.2]
 [5.6 2.9 3.6 1.3]
 [5.6 3.  4.

12. Знайти найбільш часто повторюване значення в массиві

In [441]:
flatten_combine = combine.flatten()
unique_values, counts = np.unique(flatten_combine, return_counts=True)
most_frequent_index = np.argmax(counts)
print("Most freq value = ", unique_values[most_frequent_index])

Most freq value =  3.0


13. Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.

In [442]:
def fn(data, column_index):
    mean_value = np.mean(data[:, column_index])
    data[:, column_index] = np.where(
        data[:, column_index] < mean_value,
        data[:, column_index] * 2,
        data[:, column_index] / 4
    )
    
    return data

14. Застосувати отриману функцію до 3-ї колонки

In [443]:
fn(combine, 2)

array([[4.3  , 3.   , 2.2  , 0.   ],
       [4.4  , 2.9  , 2.8  , 0.   ],
       [4.4  , 3.2  , 2.6  , 0.2  ],
       [4.4  , 3.   , 2.6  , 0.2  ],
       [4.5  , 2.3  , 2.6  , 0.3  ],
       [4.6  , 3.1  , 3.   , 0.2  ],
       [4.6  , 3.4  , 2.8  , 0.3  ],
       [4.6  , 3.2  , 2.8  , 0.2  ],
       [4.6  , 3.6  , 0.   , 0.2  ],
       [4.7  , 3.2  , 2.6  , 0.2  ],
       [4.7  , 3.2  , 3.2  , 0.2  ],
       [4.8  , 3.   , 2.8  , 0.1  ],
       [4.8  , 3.   , 0.   , 0.3  ],
       [4.8  , 0.   , 3.8  , 0.2  ],
       [4.8  , 3.1  , 3.2  , 0.2  ],
       [4.8  , 3.4  , 3.2  , 0.2  ],
       [4.9  , 3.1  , 3.   , 0.1  ],
       [4.9  , 3.1  , 3.   , 0.1  ],
       [4.9  , 2.4  , 6.6  , 1.   ],
       [4.9  , 3.1  , 3.   , 0.1  ],
       [4.9  , 3.   , 2.8  , 0.2  ],
       [5.   , 3.5  , 3.2  , 0.6  ],
       [5.   , 3.3  , 2.8  , 0.2  ],
       [5.   , 3.5  , 2.6  , 0.3  ],
       [5.   , 3.4  , 3.   , 0.2  ],
       [5.   , 3.   , 3.2  , 0.2  ],
       [5.   , 3.4  , 3.2  , 0.4  ],
 